name: Check Missing Translations

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x' # Use a versão do Flutter do seu projeto
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Check for untranslated messages
        run: |
          flutter gen-l10n
          if [ -f lib/l10n/untranslated_messages.txt ] && [ "$(cat lib/l10n/untranslated_messages.txt | tr -d '[:space:]')" = "{}" ]; then
            echo "✅ All translations are up to date. No missing keys found.";
          else
            echo "❌ Missing translations detected. Please add the missing keys.";
            exit 1;
          fi